### PR TITLE
fix feed update

### PR DESCRIPTION
**Pull request by wc7086**
https://forum.openwrt.org/t/package-feed-error/101391/2

### CODE REVIEW

**Comment by wc7086** [comment]
close #445

**Comment by muink** [comment]
But this is not a collection of packages, just a single package
The correct thing to do is to put it into `package/`. [The ref](https://github.com/muink/luci-app-einat?tab=readme-ov-file#build)
Or build a collection. [The ref2](https://github.com/fantastic-packages/packages/blob/master/feeds/luci/luci-theme-argon)

**Comment by wc7086** [comment]
Deprecated PKG fields can also cause this problem, and now commit has been changed to delete only deprecated PKG fields

**Comment by kyogithub** [comment]
Also the release actions should be updated because they uses the PKG_VERSION variable to tag the release files... with that removed the actions now doesn't work

**Comment by wc7086** [comment]
> Also the release actions should be updated because they uses the PKG_VERSION variable to tag the release files... with that removed the actions now doesn't work

Sorry, I'm not familiar enough with LUCI. I hope you can submit a PR to fix this issue.

**Comment by SpeedPartner** [comment]
This commit is incorrect ...
Please do not add this theme, which is a standalone package, to feeds.conf.default; it is not a collection of packages, and it is not a feed**s.**

**Pull request merged**
