### PR TITLE
Adjust text inside progressbar in small screens

### PR DESCRIPTION
**Pull request by McGiverGim**
When under 768px, the text inside the progressbar is not centered.

This change centers the text for this small screens and makes the text slighty bigger.

This is before, in the status:
image

And after:
image

The same for software, before:
image

And after:
image

### CODE REVIEW

**Comment by castillofrancodamian** [comment]
In dark mode it does not appear aligned.

**Comment by McGiverGim** [comment]
It seems dark mode has smaller progress bar? If I have time I will try to look at it.

**Comment by castillofrancodamian** [comment]
> It seems dark mode has smaller progress bar? If I have time I will try to look at it.

I have also noticed these other errors.

**Comment by castillofrancodamian** [comment]
Screenshot_20220603_165205

**Comment by McGiverGim** [comment]
@castillofrancodamian I'm not having time right now to try to help with this... I will try in some weeks.
I suggest copy all this as an issue, maybe others can help with this until I can take a look to it. This PR is closed so nobody will see it.

**Pull request merged**
