### PR TITLE
Disable CSStidy for compilation

### PR DESCRIPTION
**Pull request by muink**
Simply fix the problem that the font does not take effect (css3 feature is broken by CSStidy)
@jerrykuku @SpeedPartner

### CODE REVIEW

**Comment by SpeedPartner** [comment]
Sorry, I'm only responsible for maintaining branch 18.06 for the time being🙏

**Comment by castillofrancodamian** [comment]
@SpeedPartner It's very old 18.06.

**Comment by muink** [comment]
Well, I can only wait for @jerrykuku to see the PR
Will CSStidy need to be turned off in 18.06? @SpeedPartner

**Comment by SpeedPartner** [comment]
> Well, I can only wait for @jerrykuku to see the PR Will CSStidy need to be turned off in 18.06? @SpeedPartner

It doesn't seem necessary, tks~😘

**Pull request merged**
