### PR TITLE
Enhance wallhaven.cc features and fix update for Unsplash

### PR DESCRIPTION
**Pull request by AcidSlide**
- Allow using **Tag ID** for specific sets of wallpapers (similar with unsplash using category id)
- Allow use of users personal apikey (for registered wallhaven users) to remove limits in retrieving images especially when using Tag ID
- Enable switching from exact resolution to minimum resolution instead

_Note: In line 58 to 60, this is a hack which I'm not sure if I'm the only one encountering when using Microsoft Edge specifically for wallhaven.cc only.  It seems there are times (after investigating using the developer tools), first pull of the image as background results in a 403 (forbidden).  But calling the generated url for the image manually will results in proper loading._

**Update [2023-06-30]:  Unsplash wallpaper URL fix**
- **Reason**: https://source.unsplash.com has been deprecated and doesn't work anymore
- **New Requirement**: To use Unslash in needs a developer access key and use the https://api.unsplash.com
- Changes are based on the this documentation from Unsplash: [https://unsplash.com/documentation#get-a-random-photo](https://unsplash.com/documentation#get-a-random-photo)
- To create/get an access key, follow this documentation: https://unsplash.com/documentation#creating-a-developer-account

### CODE REVIEW

**Comment by AcidSlide** [comment]
A sample `/etc/argon/config` file using wallhaven.cc

```

config global
        option bing_background '1'
        option online_wallpaper 'wallhaven_109730'
	option use_api_key '--redacted--'
	option use_exact_resolution '0'
        option primary '#5e72e4'
        option dark_primary '#483d8b'
        option blur '10'
        option blur_dark '10'
        option transparency '0.5'
        option transparency_dark '0.5'
        option mode 'normal'
```

The above loads list of images from **#landscape** which has a corresponding tag id of `id:711`.  You can check using this link: https://wallhaven.cc/search?q=id%3A711&sorting=random&ref=fp&seed=MCfMTb&page=2

**Comment by eth54321** [comment]
Thanks for the quick response to my issue. Much appreciated.

**Comment by AcidSlide** [comment]
> Thanks for the quick response to my issue. Much appreciated.

Uhm what issue?

**Comment by AcidSlide** [comment]
I've updated the script again since unsplash has deprecated the original url used for retrieving images from unsplash.  See first comment for details.

**Comment by easyteacher** [comment]
https://source.unsplash.com/ is working again

**Comment by AcidSlide** [comment]
> https://source.unsplash.com/ is working again

I'll adjust the patch so it both can use the source.unsplash.com and api.unsplash.com depending on the config

**Pull request merged**
